name: cape
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - tqdm=4.66.4
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchtext=0.18.0
  - pytorch-cuda=12.1
  - pillow=10.3.0
  - timm=1.0.21
  - pyarrow=17.0.0
  - pip
  - pip:
      - matplotlib==3.9.0
      - datasets==3.2.0
